version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          filters:
            branches:
              only:
                - master
                - main
          account-url: AWS_ECR_ACCOUNT_URL
          dockerfile: Dockerfile
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: AWS_DEFAULT_REGION
          tag: "latest"
